version: '3.7'
services:
  application:
    image: test2
    environment:
    - CERT=              #(comment out this line to enable https)
    ports:
    - 8888:8888
    volumes:
    - notebooks:/notebooks
    - config:/root/.jupyter
    - pkgs:/root/miniconda3/pkg
    - lib:/root/miniconda3/lib

    restart: unless-stopped
volumes:
  notebooks:
  config:
  pkgs:
  lib:

