version: '3.7'
services:
  application:
    image: m400/jupyterlab
    ports:
    - 8888:8888
    volumes:
    - notebooks:/notebooks
    - config:/root/.jupyter
    - pkgs:/root/miniconda3/pkg
    - lib:/root/miniconda3/lib
    #- miniconda3:/root/miniconda3  #optional
    restart: unless-stopped
volumes:
  notebooks:
  config:
  pkgs:
  lib:
